sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls

script:
- pycodestyle uw_panopto/
- coverage run --source=uw_panopto uw_panopto/test.py -v

after_script:
- coveralls
before_deploy:
- find uw_panopto/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_panopto/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: "ZLqWOj9hpGU7v7MqFxhlJqi03od98wGkXVVrImqHmuFkgUSyuFGhhQrGokF1lyY9gTHukTG2t3CaVJv1dvxjLIlsAXHhiV3SSArwmf2GeRANbVyGy+P7FuAp7DXmgix8oE0seX4UQKRpplNHZDgxsjBqUZDwsiZIQ+wvlmvCThyfr7d58LR4KnvxQm7OxpIB37MwxD+eHk7g8Aov/3cWR5Fz82kYtNbIZkLNoasaeqsC04RWOqfc+Nh8ixFeOoYzWJlmADbDGqaGV23aTwp8DhhLpXHr6EbHgF4WcsHZWnRsVc0BAYLlZmHvlIJd+zP9PNkd/tfbRxlQr0lqTG5U5vowuIwok0OBVLn92YmnVZ757/wM40CPOTBATLz6AT6neDm1tsoCQPwWNxKxemZcDaXBdFWVmkbak0A5PPwdP6VdFiU4uKuQRj7QThjx7IEWGErsot9gMHfP+oEzuF7rQrUCTE2/fHGhF20TROduxKRKtSgHCQim80a3EsJC95FBy7wYQTZ7ZMOfXfBeE2HTscLMK9e+KsxgRX53JTfQsf1yNKGnzUGHClTlnPipTGNP+bgteahuN74JBKg8XvtHKejozgZd3BA8TcvrPR78a2lWF4tNDAchHeA9i8KRnLTn1suGLVf5ntwRJl6q4ZZzB1lb4Iet2Ent9ND0TsluJDE="
  on:
    tags: true
    python: '3.6'
