sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls

script:
- pycodestyle uw_panopto/
- coverage run --source=uw_panopto uw_panopto/test.py -v

after_script:
- coveralls
before_deploy:
- find uw_panopto/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_panopto/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: 
  on:
    tags: true
    python: '3.6'
